# Generated by Django 4.1.4 on 2022-12-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contactInformation', models.CharField(max_length=200)),
                ('lastViolation', models.DateTimeField(verbose_name='last Violation')),
            ],
        ),
    ]
