# Generated by Django 4.1.4 on 2022-12-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_owner_closestviolation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='id',
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
