# Generated by Django 4.1.4 on 2023-01-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_owner_id_alter_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
